PC-597: Creating a master CSV for Consortium leads in addition to individual CSVs
UKGovernmentBEIS/desnz-home-energy-retrofit-portal-beta pull request #83
Opened 2024-02-01 10:39 UTC by samyou-softwire

closes PC-597

![image](https://github.com/UKGovernmentBEIS/desnz-home-energy-retrofit-portal-beta/assets/108681823/0a28150d-121f-4ac4-93c0-30c8007337f0)

queries which consortiums the user manages and if any exist, it will collate a csv download on the downloads page per month per consortium

for this ticket I defined a consortium lead such that a user is a consortium lead IIF they are a lead for every LA in a consortium, which I believe is how they are implemented on live

some new consortium data was added to the admin portal, yielded from the provided dsa tracker spreadsheet. this includes consortium name, and consortium member LAs. for easy querying a dictionary of consortium to LAs as well as LA to parent consortium was added

to support items on the menu of two different download types an abstract parent class was added for csv files. this contains generic information about the file download and is concretely implemented by consortiums & LAs

the csv files are generated using the added CsvHelper package. the consortium csv files have a new column as well for their yielded consortium as this is not included in the LA csv files

on the frontend, consortiums can be identified as their name ends (Consortium). they appear in the filter, though the ticket did not specify how exactly filtering by consortium should work. for now, the implemented option is that when filtering out the consortium it will only remove the consortium csv, and not do any additional filtering on the LA csv downloads in that consortium

this pr does not contain new tests

2024-02-01 17:06 UTC, samyou-softwire commented
for generating the consortium data the following kotlin code was written (requiring an input csv of LA information)
[desnz-consortium-parser.zip](https://github.com/UKGovernmentBEIS/desnz-home-energy-retrofit-portal-beta/files/14128502/desnz-consortium-parser.zip)

2024-02-01 17:30 UTC, jamiehumphries requested changes
There's quite a lot that it would be good to revisit and tidy up, but I've just put a few comments on bits that we can fix up quickly before this release.

2024-02-02 09:48 UTC, samyou-softwire commented on HerPortal.BusinessLogic/Models/ConsortiumData.cs
> +    // on https://www.ordnancesurvey.co.uk/business-government/tools-support/addressbase-support
oops

2024-02-02 09:49 UTC, samyou-softwire commented on HerPortal.BusinessLogic/Models/LocalAuthorityData.cs
> +    public static readonly Dictionary<string, string> LocalAuthorityConsortiumCodeByCustodianCode = new()
done

out of interest, any particular reason to now define a separate function to generate the dictionary?

2024-02-02 09:49 UTC, samyou-softwire commented on HerPortal.BusinessLogic/Services/CsvFileService/AbstractCsvFileData.cs
> +public abstract class AbstractCsvFileData
is now CsvFileData

2024-02-02 10:41 UTC, LadunOmideyiSoftwire approved these changes

2024-02-02 11:26 UTC, merged